### ISSUE TITLE
DST crashes when starting with NucleousCoop

### ISSUE THREAD

**Issue by JoaoLages** [lucasassislar/nucleuscoop#143]
Hi there! I am trying to run Don't Starve Together (DST) with 2 controllers. Once I get them recognized by NucleousCoop and start the game, it crashes before starting.

Here is the log generated:

```
[Header]

Saturday, June 6, 2020

1:30:29 PM

Nucleus Coop Alpha v8

[Message]

Process has exited, so the requested information is not available.

[Stacktrace]

at System.Diagnostics.Process.EnsureState(State state)

at System.Diagnostics.Process.get_MainWindowHandle()

at Nucleus.Gaming.GenericGameHandler.Play()

at Nucleus.Gaming.GameManager.play(Object state)
```
How can I fix this? Would really like to play DST with my friends!

**Comment by Snailedlt** [comment]
Hi, did you follow this guide? https://www.reddit.com/r/localmultiplayergames/comments/axxpb9/dont_starve_together_4_player_splitscreen_on_pc/

If so, please report the issue either on reddit, or in our discord for a quicker and better response

**Comment by JoaoLages** [comment]
Yes, I followed. The game crashes right when I press 'Play' on NucleousCoop

I have also posted my issue on Reddit but got no comments:
https://www.reddit.com/r/nucleuscoop/comments/gxq6fj/nucleouscoop_crashes_when_starting_dont_starve/

**Comment by Snailedlt** [comment]
Hmm, in that case I'd try in the discord, usually the best place for technical support.
https://discord.gg/ZaRb3e

**Comment by JoaoLages** [comment]
@Snailedlt can you send me the invite to discord again please? the link is no longer valid. thanks

**Comment by Snailedlt** [comment]
https://discord.gg/KFPkgtb
